### ISSUE TITLE
M1R 1.1.5 What are the great things that your team is doing? [Joachim]

### ISSUE THREAD

**Issue by joachimsofjan** [joachimsofjan/INF2001_P5-3#76]
Description: This is an insight/reflection about what we have done well as a team.

**Comment by joachimsofjan** [comment]
We trusted each other and did what we needed to do

**Comment by halilah1** [comment]
yes! there is a lot of trust

**Comment by kevanO297** [comment]
Thank you for your trust lets continue this trusts among teammates for next milestones!

**Comment by wyvernk** [comment]
Yes trust is the key to success and we definitely had it!

**Comment by SikesJohn** [comment]
Certainly, cohesion did serve us well in this assignment.
