### ISSUE TITLE
M1R 1.2.5 Are there any thing in the team that wish could be changed? [Joachim]

### ISSUE THREAD

**Issue by joachimsofjan** [joachimsofjan/INF2001_P5-3#77]
Description: This is an insight/reflection about what we have could have done better as a team

**Comment by joachimsofjan** [comment]
We should have followed more closely with the client and could have reacted to any changes

**Comment by kevanO297** [comment]
I agree, we should have followed exactly what the client mentioned instead of following the project brief. Lets work hard to adhere to clients requirements in the future!

**Comment by wyvernk** [comment]
Agreed, the client is always right! Hence we should have followed whatever he said

**Comment by halilah1** [comment]
yes client always final say

**Comment by SikesJohn** [comment]
Yes I concur, the client is king for projects like these.
