### ISSUE TITLE
M1R 1.3.5 What will we commit to improve in the next milestone? [Joachim]

### ISSUE THREAD

**Issue by joachimsofjan** [joachimsofjan/INF2001_P5-3#78]
Description: This is the things I will work towards improving on.

**Comment by joachimsofjan** [comment]
Be more proactive in closing up outside influences such as changes in scope, lecture information and any change stated by professors

**Comment by kevanO297** [comment]
Lets discuss as a group questions to clarify with Prof Serena for next milestones!

**Comment by wyvernk** [comment]
Yes being proactive will help us adapt to changed faster!

**Comment by halilah1** [comment]
Yes we definitely need to keep up with the changes and update accordingly

**Comment by SikesJohn** [comment]
Clearing up our doubts on the provided materials would have allowed us to get more work done earlier for our project.
