### ISSUE TITLE
M1R 1.1.3 What are the great things that your team is doing? [Wyvern]

### ISSUE THREAD

**Issue by wyvernk** [joachimsofjan/INF2001_P5-3#79]
Description: This is an insight/reflection about what we have done well as a team

**Comment by wyvernk** [comment]
- We have good communication.
- We regularly organize meetings to check on each other's progress.

**Comment by kevanO297** [comment]
Yes, hope we can continue to this do this in future milestones!

**Comment by halilah1** [comment]
yes very good communication

**Comment by joachimsofjan** [comment]
I look forward to continuing the work with you

**Comment by SikesJohn** [comment]
I concur! We should strive to keep up the the good work.
