### ISSUE TITLE
M1R 1.3.3 What will we commit to improve in the next milestone? [Wyvern]

### ISSUE THREAD

**Issue by wyvernk** [joachimsofjan/INF2001_P5-3#80]
Description: This are what we will commit to improve in the next milestone.

**Comment by wyvernk** [comment]
- We can ask the professor more questions to clarify our doubts about the project 
- We can search online for more materials to aid us in our projects

**Comment by joachimsofjan** [comment]
Yes! I agree that this is something we should do. Let's push each other into hitting our goals

**Comment by halilah1** [comment]
Yes we can definitely can search online

**Comment by SikesJohn** [comment]
Certainly, clarifying our doubts early will definitely help us work efficiently going forward.

**Comment by kevanO297** [comment]
I concur, lets work even harder in milestone 2 !
