### ISSUE TITLE
M1R 1.1.2 What are the great things that your team is doing [Kevan]

### ISSUE THREAD

**Issue by kevanO297** [joachimsofjan/INF2001_P5-3#81]
Description: This is an insight/reflection about what we have done well as a team.

**Comment by kevanO297** [comment]
- Our team dynamics are great, we communicated effectively throughout the process of doing M1. Ensuring that everyone is up to date of the expectations of the project.
- Consistent team meetings.
- Care for teammates (Psychological care, physiological care)
- Tasks was done on time, consistently, not last minute rushed.

**Comment by halilah1** [comment]
I agree! Our team is so united!

**Comment by joachimsofjan** [comment]
I have enjoyed going through M1 with you, let us continue on this pace towards M2 and M3

**Comment by wyvernk** [comment]
Indeed! Our team is well coordinated

**Comment by SikesJohn** [comment]
Yes, the team dynamics and accountability so far have been great.
