### ISSUE TITLE
M1R 1.2.2 Are there any thing in the team that wish could be changed? [Kevan]

### ISSUE THREAD

**Issue by kevanO297** [joachimsofjan/INF2001_P5-3#82]
Description: This are the future envisioned changes that hopefully we would commit to.

**Comment by kevanO297** [comment]
- As a team we can pay more attention to the lecture to understand the contents better
- Participate in lectures to test our understanding
- Do internet research and use our discerning skills to find out what is right and wrong
- Read the referenced textbook

**Comment by joachimsofjan** [comment]
I agree with you! Let us push each other towards our end goal and leave no man behind

**Comment by wyvernk** [comment]
Yes we should do more to try and understand the content given

**Comment by halilah1** [comment]
yes need to do research beforehand

**Comment by SikesJohn** [comment]
Yes, more proactive research would have made our experience with M1 easier.
