### ISSUE TITLE
M1R 1.3.2 What will we commit to improve in the next milestone? [Kevan]

### ISSUE THREAD

**Issue by kevanO297** [joachimsofjan/INF2001_P5-3#83]
Description: This are what we will commit to improve in the next milestone.

**Comment by kevanO297** [comment]
- We will commit to asking more questions during the lessons
- We will commit to ask questions and get answers from Prof Serena more consistently at each diagrams we created and not nearing the end of the milestone.

**Comment by joachimsofjan** [comment]
Sure ! This is something I also agree that we should commit towards doing this

**Comment by wyvernk** [comment]
Yes! We should indeed ask more questions to aid in our understanding

**Comment by halilah1** [comment]
yes we definitely need to ask questions with better justification
