### ISSUE TITLE
M1R 1.2.3 Are there any thing in the team that wish could be changed? [Wyvern]

### ISSUE THREAD

**Issue by wyvernk** [joachimsofjan/INF2001_P5-3#84]
Description: This are the future envisioned changes that hopefully we would commit to.

**Comment by wyvernk** [comment]
- We could have clarified with the professor about some of our doubts.
- We should looked up for more materials to help our understanding of the topics

**Comment by joachimsofjan** [comment]
This is something I wholeheartedly agree with. In the future, let us do so and have a fruitful time in the process of this project

**Comment by halilah1** [comment]
yes definitely need more research

**Comment by SikesJohn** [comment]
I agree completely, we had to get a good understanding before we made any meaningful progress on the report.

**Comment by kevanO297** [comment]
I agree, lets work hard together on milestone 2 and also continue what we have done well in milestone 1!
