### ISSUE TITLE
M1R 1.2.4 Are there any thing in the team that wish could be changed? [Kevin]

### ISSUE THREAD

**Issue by SikesJohn** [joachimsofjan/INF2001_P5-3#85]
Description: This are the future envisioned changes that hopefully we would commit to.

**Comment by SikesJohn** [comment]
We should consider what is needed more carefully for each stage of the submission, so as to not waste effort working on items that do not need to be submitted. 

We should have consulted the lecturers about topics that may not have been fully addressed by the slides and lectures.

There was a gap in our understanding from what we gathered from the client meetings, we should have been more dedicated to adhering to the needs of the client over what was stated in the brief.

The team should have become clearer on what was expected of us in the use case diagram's design.

**Comment by kevanO297** [comment]
Yes! Lets work hard to bridge these gaps you mentioned!

**Comment by wyvernk** [comment]
Indeed, we should have consulted our lecturers more about the topics learned

**Comment by halilah1** [comment]
yes we need to close the gap
