### ISSUE TITLE
M1R 1.1.1 What are the great things that your team is doing? [Halilah]

### ISSUE THREAD

**Issue by halilah1** [joachimsofjan/INF2001_P5-3#86]
Description: This is an insight/reflection about what we have done well as a team.

**Comment by halilah1** [comment]
-  A lot of meetings to discuss

- Straight to the point communication among members

- Great emotional support

**Comment by kevanO297** [comment]
I agree! Love our commitments to meetings!

**Comment by joachimsofjan** [comment]
Well said! I hope we can continue working towards our goal in this way

**Comment by wyvernk** [comment]
Agreed! We have a great team dynamic

**Comment by SikesJohn** [comment]
True, these points have allowed us to meet the deadlines well thus far.
