### ISSUE TITLE
M1R 1.1.4 What are the great things that your team is doing? [Kevin}

### ISSUE THREAD

**Issue by SikesJohn** [joachimsofjan/INF2001_P5-3#87]
Description: This is an insight/reflection about what we have done well as a team.

**Comment by SikesJohn** [comment]
We had good communication as a team as every one particapated actively and contributed to the discussion. We met frequently and actively to update each other and collaborate on the report.

**Comment by kevanO297** [comment]
I love your background in UI design, its has been extremely helpful in giving a different perspective.

**Comment by joachimsofjan** [comment]
I admire the hard work you have put into this submission

**Comment by wyvernk** [comment]
I appreciate the extra mile of effort you put in to this project for our UI design!

**Comment by halilah1** [comment]
Yes! good communication in team
