### ISSUE TITLE
M1R 1.3.4 What will we commit to improve in the next milestone? [Kevin]

### ISSUE THREAD

**Issue by SikesJohn** [joachimsofjan/INF2001_P5-3#88]
Description: This are what we will commit to improve in the next milestone.

**Comment by SikesJohn** [comment]
We should commit to consulting the professor more often and earlier to clear up misconceptions that we may have.

We should commit to checking carefully before starting work on a section of the project.

We should commit to adhering to the client's wishes word for word over the project brief.

**Comment by joachimsofjan** [comment]
You raise up very valid points that I agree we should be committing on

**Comment by wyvernk** [comment]
Indeed! By committing to consulting the professor we can clarify our doubts faster and it will help us finish our project more smoothly

**Comment by halilah1** [comment]
Yes I agree client has the final say
