### ISSUE TITLE
M1R 1.2.1 Are there any thing in the team that wish could be changed? [Halilah]

### ISSUE THREAD

**Issue by halilah1** [joachimsofjan/INF2001_P5-3#89]
Description: This are the future envisioned changes that hopefully we would commit to.

**Comment by halilah1** [comment]
- the requirements gathering from the client should have better questions 
- planning the task could be a lot better
- ask better questions for prof
- have better justification for what we do

**Comment by kevanO297** [comment]
I will try to improve myself and the team as group leader! Sorry didn't meet your expectation for planning tasks.

**Comment by joachimsofjan** [comment]
Let us work towards hitting all our goals and improve on M2

**Comment by wyvernk** [comment]
Indeed! We should clarify our doubts more often

**Comment by SikesJohn** [comment]
We would do well to take these points into consideration for future projects.
