### ISSUE TITLE
M1R 1.3.1 What will we commit to improve in the next milestone? [Halilah]

### ISSUE THREAD

**Issue by halilah1** [joachimsofjan/INF2001_P5-3#90]
Description: These are what we will commit to improve in the next milestone.

**Comment by halilah1** [comment]
- Do the tasks earlier to complete M2 faster

**Comment by joachimsofjan** [comment]
I agree, let us work together and spur each other onto finishing what we set out to do!

**Comment by wyvernk** [comment]
Agreed, we should have finished faster so we had more time to clarify our doubts

**Comment by SikesJohn** [comment]
Yes, we would do well to start earlier on the project to cater to unexpected developments in out projects.
